// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRoPc4U05xY2bDtuJcmuDmLQoWw1k135Y',
    appId: '1:867001886606:web:43480e48a415dab3e366df',
    messagingSenderId: '867001886606',
    projectId: 'project-medi-doc-mini',
    authDomain: 'project-medi-doc-mini.firebaseapp.com',
    storageBucket: 'project-medi-doc-mini.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxi7mTxefuoTxFgz_MdgXBJEUzbb0-Dco',
    appId: '1:867001886606:android:01f1d5cf5019a4dbe366df',
    messagingSenderId: '867001886606',
    projectId: 'project-medi-doc-mini',
    storageBucket: 'project-medi-doc-mini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLqARqZ4_uI8eumxdJHH06cNdRxHGMeI',
    appId: '1:867001886606:ios:5511c77e6122f4dbe366df',
    messagingSenderId: '867001886606',
    projectId: 'project-medi-doc-mini',
    storageBucket: 'project-medi-doc-mini.appspot.com',
    iosClientId: '867001886606-8a80lmqj0gfhj2bs1hrd1qb412ab30pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeLqARqZ4_uI8eumxdJHH06cNdRxHGMeI',
    appId: '1:867001886606:ios:5511c77e6122f4dbe366df',
    messagingSenderId: '867001886606',
    projectId: 'project-medi-doc-mini',
    storageBucket: 'project-medi-doc-mini.appspot.com',
    iosClientId: '867001886606-8a80lmqj0gfhj2bs1hrd1qb412ab30pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicDoc',
  );
}
